# 开发配置
# 设置http访问端口
server:
    port: 8080
# 设置https访问端口
https:
    port: 8888
    ssl:
        key-store: classpath:server.keystore
        key-alias: tomcat
        key-store-password: 123456
        key-password: 123456
        key-store-type: JKS
spring:
    servlet:
        multipart:
            # 设置单个文件最大内存
            max-file-size: "10MB"
            # 设置所有文件最大内存
            max-request-size: "10MB"
    redis:
        host: localhost
        port: 6379
        jedis:
            pool:
                ## 连接池中的最大空闲连接
                max-idle: 8
                ## 连接池中的最小空闲连接
                min-idle: 0
                ## 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                ## 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1
    datasource:
        name: collection_data
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
            #监控统计拦截的filters
            filters: stat
            driver-class-name: com.mysql.jdbc.Driver
            #基本属性
            url: jdbc:mysql://127.0.0.1:3306/collection_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
            username: root
            password: 123456
            #配置初始化大小/最小/最大
            initial-size: 1
            min-idle: 1
            max-active: 20
            #获取连接等待超时时间
            max-wait: 60000
            #间隔多久进行一次检测，检测需要关闭的空闲连接
            time-between-eviction-runs-millis: 60000
            #一个连接在池中最小生存的时间
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
            pool-prepared-statements: false
            max-pool-prepared-statement-per-connection-size: 20



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.jayson.collection.domain  # 注意：对应实体类的路径